### ISSUE TITLE
[CHORE] initialize QuickReplies App  

### ISSUE THREAD

**Issue by VipinDevelops** [RocketChat/Apps.QuickReplies#1]
### Task :rocket: 

- [ ] Initialise RC App
- [ ]  Add Icon
- [ ]  Add  bug form
- [ ]  Add  feat form
- [ ]  Add PR template
- [ ]  Set up eslint & prettier
